<a href="https://colab.research.google.com/github/OmkarKatkade/TensorFlow_Repo/blob/main/TensorFlow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING TENSORFLOW 2.0

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf  # now import the tensorflow module
print(tf.version)

Tensors are generalized vectors and matrices ranked to their highest dimensions. Internally, TensorFlow represents tensors in n-dimensional arrays of base datatypes. Each tensors represnts a partially defined computation that will eventually produce a value.

Each Tensor has a data type and shape associated with it.
1. Data Type: float32, int32, string and others
2. Shape: Represents no. of elements in each dimension.

In [ ]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.21, tf.float32)

print(string)
print(number.dtype)
print(floating.value)

Rank/Degree of tensor is the no.of dimensions involved in the tensor. Above created tensors have a rank 0 aka Scalar.
Below are examples of rank 1 and rank 2 tensors. Also, shape represents the no.of elements in each dimension of the tensor.

In [28]:
rank1_tensor = tf.Variable(["Omkar","Katkade"], tf.string)
rank2_tensor = tf.Variable([["Omkar","Katkade","o"], ["Arun","Katkade","o"], ["Chatur", "Katkade","o"]], tf.string)
print(tf.rank(rank1_tensor))
print(rank2_tensor.shape)
print(tf.rank(rank2_tensor))

tf.Tensor(1, shape=(), dtype=int32)
(3, 3)
tf.Tensor(2, shape=(), dtype=int32)


RESHAPING TENSORS:

In [ ]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3,-1])
print(tensor1)
print(tensor2)
print(tensor3)

**SLICING THE TENSOR:**
Below code is self-explanatory

In [31]:
matrix = [ [1, 2, 3, 4, 5],
           [6, 7, 8, 9, 10],
           [11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20] ]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tensor.shape)
print(tf.rank(tensor))

(4, 5)
tf.Tensor(2, shape=(), dtype=int32)


In [32]:
three = tensor[0, 2]
row1 = tensor[0]
col1 = tensor[:, 0]
row2N4 = tensor[1::3]
print(three)
print(row1)
print(col1)
print(row2N4)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor([[ 6  7  8  9 10]], shape=(1, 5), dtype=int32)


***Types of Tensors***

These are the most used and we will talk more in depth about each as they are used.

Variable
Constant
Placeholder
SparseTensor
With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.